const mockBigCarousel = [
  {
    backdrop_path: "/35SS0nlBhu28cSe7TiO3ZiywZhl.jpg",
    first_air_date: "2018-05-02",
    genre_ids: [10759, 18],
    id: 77169,
    name: "Cobra Kai",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Cobra Kai",
    overview:
      "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
    popularity: 4977.824,
    poster_path: "/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg",
    vote_average: 8.1,
    vote_count: 3885,
  },
  {
    backdrop_path: "/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    first_air_date: "2019-12-20",
    genre_ids: [10765, 18, 10759],
    id: 71912,
    name: "The Witcher",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    popularity: 986.496,
    poster_path: "/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    vote_average: 8.2,
    vote_count: 3208,
  },
  {
    backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    first_air_date: "2021-09-17",
    genre_ids: [10759, 9648, 18],
    id: 93405,
    name: "Squid Game",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    popularity: 894.755,
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    vote_average: 7.8,
    vote_count: 9723,
  },
  {
    backdrop_path: "/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg",
    first_air_date: "2016-01-25",
    genre_ids: [80, 10765],
    id: 63174,
    name: "Lucifer",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    popularity: 978.971,
    poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    vote_average: 8.5,
    vote_count: 11248,
  },
  {
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    first_air_date: "2017-05-02",
    genre_ids: [80, 18],
    id: 71446,
    name: "Money Heist",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    popularity: 657.331,
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    vote_average: 8.3,
    vote_count: 15794,
  },
  {
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    first_air_date: "2021-11-06",
    genre_ids: [16, 10765, 10759, 18],
    id: 94605,
    name: "Arcane",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    popularity: 663.141,
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    vote_average: 9.1,
    vote_count: 1451,
  },
  {
    backdrop_path: "/bxU79lpl8ZQAVJ72155kqWkuqMu.jpg",
    first_air_date: "2019-01-11",
    genre_ids: [35, 18],
    id: 81356,
    name: "Sex Education",
    origin_country: ["GB"],
    original_language: "en",
    original_name: "Sex Education",
    overview:
      "Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school.",
    popularity: 550.392,
    poster_path: "/8j12tohv1NBZNmpU93f47sAKBbw.jpg",
    vote_average: 8.4,
    vote_count: 5259,
  },
  {
    backdrop_path: "/bfXTYu3oLtEUL0jAxgx7Jy56yHl.jpg",
    first_air_date: "2021-11-19",
    genre_ids: [18, 80, 9648, 10765],
    id: 106651,
    name: "Hellbound",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "지옥",
    overview:
      "Unearthly beings deliver bloody condemnations, sending individuals to hell and giving rise to a religious group founded on the idea of divine justice.",
    popularity: 483.247,
    poster_path: "/5NYdSAnDVIXePrSG2dznHdiibMk.jpg",
    vote_average: 7.6,
    vote_count: 392,
  },
  {
    backdrop_path: "/eAZtz2ydxBaHtJw3J42Gdy2DSpc.jpg",
    first_air_date: "2021-01-20",
    genre_ids: [35, 18],
    id: 115857,
    name: "Daughter from Another Mother",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Madre solo hay dos",
    overview:
      "After realizing their babies were exchanged at birth, two women develop a plan to adjust to their new lives: creating a single —and peculiar— family.",
    popularity: 525.653,
    poster_path: "/6chvnAakKI2cYW69ODBHZHm8clb.jpg",
    vote_average: 7.5,
    vote_count: 993,
  },
  {
    backdrop_path: "/4xDgA9HpGXXxqLP6VFb2qdQnWPN.jpg",
    first_air_date: "2021-12-23",
    genre_ids: [9648, 35],
    id: 137571,
    name: "Elite Short Stories: Patrick",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Elite Histórias Breves: Patrick",
    overview:
      "Away from school, during the winter holidays, three new stories take place while the Las Encinas students celebrate Christmas.",
    popularity: 368.263,
    poster_path: "/vO9RpGaoi00FXQSDWAE1cfLO2S3.jpg",
    vote_average: 7.1,
    vote_count: 22,
  },
  {
    backdrop_path: "/hNj7EzEQyttoPBpYlLTkATnIiab.jpg",
    first_air_date: "2018-10-05",
    genre_ids: [80, 9648, 18],
    id: 76669,
    name: "Elite",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Élite",
    overview:
      "When three working class kids enroll in the most exclusive school in Spain, the clash between the wealthy and the poor students leads to tragedy.",
    popularity: 388.061,
    poster_path: "/3NTAbAiao4JLzFQw6YxP1YZppM8.jpg",
    vote_average: 8.2,
    vote_count: 7812,
  },
  {
    backdrop_path: "/iW74tZ8y2qobdpt4J9UQ71sw8q7.jpg",
    first_air_date: "2020-10-02",
    genre_ids: [18, 35],
    id: 82596,
    name: "Emily in Paris",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Emily in Paris",
    overview:
      "When ambitious Chicago marketing exec Emily unexpectedly lands her dream job in Paris, she embraces a new life as she juggles work, friends and romance.",
    popularity: 329,
    poster_path: "/Ak59Y9bzykmV0wAiwKsqrbORDBo.jpg",
    vote_average: 8.1,
    vote_count: 682,
  },
  {
    backdrop_path: "/pNCZbQ5jvCbgoBfeoSx0l5dJhIM.jpg",
    first_air_date: "2021-11-28",
    genre_ids: [18, 9648, 10765],
    id: 135864,
    name: "Elves",
    origin_country: ["DK"],
    original_language: "da",
    original_name: "Nisser",
    overview:
      "The Christmas vacation of a teenage girl and her family turns into a nightmare when they discover the ancient threat that haunts the island where they are.",
    popularity: 295.724,
    poster_path: "/6upMMT2Uz4bhJabBCWhYKESIbF4.jpg",
    vote_average: 7,
    vote_count: 99,
  },
  {
    backdrop_path: "/qALIyHsLhOh4xJn2tjNuOrwx86E.jpg",
    first_air_date: "2021-12-15",
    genre_ids: [9648, 35],
    id: 137569,
    name: "Elite Short Stories: Phillipe Caye Felipe",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Élite Historias Breves: Phillipe Caye Felipe",
    overview:
      "Away from school, during the winter holidays, three new stories take place while the Las Encinas students celebrate Christmas.",
    popularity: 276.867,
    poster_path: "/bd4YqweERz2vC6P1CNxUJCOAZQj.jpg",
    vote_average: 7.7,
    vote_count: 22,
  },
  {
    backdrop_path: "/jo6eCDDH1RrKsZlqXmxA1BKxcYJ.jpg",
    first_air_date: "2021-12-20",
    genre_ids: [9648, 35],
    id: 137570,
    name: "Elite Short Stories: Samuel Omar",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "Élite Historias Breves: Samuel Omar",
    overview:
      "Away from school, during the winter holidays, three new stories take place while the Las Encinas students celebrate Christmas.",
    popularity: 278.801,
    poster_path: "/osgUR4Z22ZAilyJivE708fhrRa4.jpg",
    vote_average: 7.2,
    vote_count: 21,
  },
  {
    backdrop_path: "/3Aj7j0xHXwGntChU1VaL9seBGIe.jpg",
    first_air_date: "2021-09-30",
    genre_ids: [16, 10759],
    id: 129600,
    name: "Baki Hanma",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "範馬刃牙",
    overview:
      "To gain the skills he needs to surpass his powerful father, Baki enters Arizona State Prison to take on the notorious inmate known as Mr. Unchained.",
    popularity: 284.487,
    poster_path: "/k3HCQALcUyxebVZcfy57BIDYXUz.jpg",
    vote_average: 8.2,
    vote_count: 87,
  },
  {
    backdrop_path: "/aGULNElJVpSru19WP2pUjopPX1U.jpg",
    first_air_date: "2021-07-28",
    genre_ids: [80, 10766],
    id: 128252,
    name: "The Snitch Cartel: Origins",
    origin_country: ["CO"],
    original_language: "es",
    original_name: "El cartel de los sapos: El origen",
    overview:
      "In Cali during the '60s and '70s, two brothers juggle family, romance and the joint pursuit of a burning ambition: to rule Colombia's drug industry.",
    popularity: 283.47,
    poster_path: "/A17Rt6BLHno0puR1QXbsSKhBfA4.jpg",
    vote_average: 7.9,
    vote_count: 218,
  },
  {
    backdrop_path: "/rcA17r3hfHtRrk3Xs3hXrgGeSGT.jpg",
    first_air_date: "2016-07-15",
    genre_ids: [10765, 9648, 18],
    id: 66732,
    name: "Stranger Things",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    popularity: 278.384,
    poster_path: "/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg",
    vote_average: 8.6,
    vote_count: 9216,
  },
  {
    backdrop_path: "/yQjO3CqZSbby6U7y3NfzrLB32rq.jpg",
    first_air_date: "2018-06-26",
    genre_ids: [16, 10759, 80, 18],
    id: 80623,
    name: "BAKI",
    origin_country: ["JP"],
    original_language: "ja",
    original_name: "バキ",
    overview:
      "While martial arts champion Baki Hanma trains hard to surpass his legendary father, five violent death row inmates descend upon Tokyo to take him on.",
    popularity: 285.901,
    poster_path: "/c79L7zCnRzDJerrlbIWkNCjA6tg.jpg",
    vote_average: 8.1,
    vote_count: 843,
  },
  {
    backdrop_path: "/9nBVkNBe4x9HKDAzxjxlIqecxCW.jpg",
    first_air_date: "2021-06-25",
    genre_ids: [18],
    id: 126280,
    name: "Sex/Life",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Sex/Life",
    overview:
      "A woman's daring sexual past collides with her married-with-kids present when the bad-boy ex she can't stop fantasizing about crashes back into her life.",
    popularity: 278.051,
    poster_path: "/2ST6l4WP7ZfqAetuttBqx8F3AAH.jpg",
    vote_average: 7.2,
    vote_count: 816,
  },
];
export { mockBigCarousel };
