const mockTrending = [
  {
    id: 634649,
    adult: false,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    genre_ids: [28, 12, 878],
    vote_count: 3510,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.4,
    release_date: "2021-12-15",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 8448.569,
    media_type: "movie",
  },
  {
    backdrop_path: "/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg",
    genre_ids: [28, 878],
    original_language: "en",
    original_title: "The Matrix Resurrections",
    poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    video: false,
    vote_average: 7.0,
    vote_count: 1698,
    overview:
      "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    release_date: "2021-12-16",
    title: "The Matrix Resurrections",
    id: 624860,
    adult: false,
    popularity: 6656.596,
    media_type: "movie",
  },
  {
    backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
    genre_ids: [35, 14, 28, 12, 878],
    original_language: "en",
    vote_count: 492,
    id: 425909,
    video: false,
    original_title: "Ghostbusters: Afterlife",
    poster_path: "/fQZxAA6PPWa2Lk9NgcO3m6QDlXQ.jpg",
    overview:
      "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
    release_date: "2021-11-11",
    vote_average: 7.2,
    title: "Ghostbusters: Afterlife",
    adult: false,
    popularity: 953.512,
    media_type: "movie",
  },
  {
    overview:
      "Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.",
    release_date: "2021-12-07",
    adult: false,
    backdrop_path: "/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg",
    vote_count: 2797,
    genre_ids: [18, 35, 878],
    original_title: "Don't Look Up",
    original_language: "en",
    id: 646380,
    poster_path: "/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg",
    title: "Don't Look Up",
    video: false,
    vote_average: 7.3,
    popularity: 1682.769,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    vote_count: 1981,
    original_language: "en",
    original_title: "Encanto",
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    vote_average: 7.8,
    video: false,
    title: "Encanto",
    release_date: "2021-11-24",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    id: 568124,
    popularity: 7239.044,
    media_type: "movie",
  },
  {
    adult: false,
    backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    poster_path: "/sR3iV0Jt080jgvPBtJhs3Tta1y9.jpg",
    video: false,
    vote_average: 6.1,
    vote_count: 686,
    overview:
      "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
    release_date: "2021-11-24",
    id: 460458,
    title: "Resident Evil: Welcome to Raccoon City",
    popularity: 7407.265,
    media_type: "movie",
  },
  {
    genre_ids: [10765, 10759],
    name: "The Book of Boba Fett",
    original_language: "en",
    first_air_date: "2021-12-29",
    poster_path: "/gNbdjDi1HamTCrfvM9JeA94bNi2.jpg",
    original_name: "The Book of Boba Fett",
    origin_country: ["US"],
    vote_average: 8.5,
    overview:
      "Legendary bounty hunter Boba Fett and mercenary Fennec Shand must navigate the galaxy’s underworld when they return to the sands of Tatooine to stake their claim on the territory once ruled by Jabba the Hutt and his crime syndicate.",
    id: 115036,
    vote_count: 195,
    backdrop_path: "/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg",
    popularity: 2041.914,
    media_type: "tv",
  },
  {
    genre_ids: [99],
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    poster_path: "/x6dEKUpJyhXu3JGHmUbfqlb7K0Y.jpg",
    id: 899082,
    vote_average: 8.6,
    vote_count: 483,
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    release_date: "2022-01-01",
    video: false,
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    adult: false,
    backdrop_path: "/8rft8A9nH43IReybFtYt21ezfMK.jpg",
    popularity: 1800.558,
    media_type: "movie",
  },
  {
    overview:
      "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
    release_date: "2021-09-30",
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    video: false,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
    vote_count: 5540,
    vote_average: 7.2,
    id: 580489,
    title: "Venom: Let There Be Carnage",
    popularity: 4681.261,
    media_type: "movie",
  },
  {
    genre_ids: [10759, 18],
    original_language: "en",
    name: "Cobra Kai",
    first_air_date: "2018-05-02",
    id: 77169,
    vote_average: 8.1,
    overview:
      "This Karate Kid sequel series picks up 30 years after the events of the 1984 All Valley Karate Tournament and finds Johnny Lawrence on the hunt for redemption by reopening the infamous Cobra Kai karate dojo. This reignites his old rivalry with the successful Daniel LaRusso, who has been working to maintain the balance in his life without mentor Mr. Miyagi.",
    original_name: "Cobra Kai",
    origin_country: ["US"],
    vote_count: 3850,
    poster_path: "/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg",
    backdrop_path: "/35SS0nlBhu28cSe7TiO3ZiywZhl.jpg",
    popularity: 5503.107,
    media_type: "tv",
  },
  {
    genre_ids: [12, 28, 53],
    original_language: "en",
    original_title: "No Time to Die",
    poster_path: "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
    video: false,
    vote_average: 7.5,
    vote_count: 2995,
    overview:
      "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
    id: 370172,
    title: "No Time to Die",
    release_date: "2021-09-29",
    adult: false,
    backdrop_path: "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
    popularity: 1046.908,
    media_type: "movie",
  },
  {
    id: 88329,
    backdrop_path: "/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg",
    original_name: "Hawkeye",
    genre_ids: [10759, 18],
    original_language: "en",
    name: "Hawkeye",
    vote_count: 1338,
    vote_average: 8.4,
    poster_path: "/pqzjCxPVc9TkVgGRWeAoMmyqkZV.jpg",
    overview:
      "Former Avenger Clint Barton has a seemingly simple mission: get back to his family for Christmas. Possible? Maybe with the help of Kate Bishop, a 22-year-old archer with dreams of becoming a superhero. The two are forced to work together when a presence from Barton’s past threatens to derail far more than the festive spirit.",
    first_air_date: "2021-11-24",
    origin_country: ["US"],
    popularity: 1509.827,
    media_type: "tv",
  },
  {
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    release_date: "2021-09-15",
    adult: false,
    backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    vote_count: 5226,
    genre_ids: [878, 12],
    original_title: "Dune",
    original_language: "en",
    id: 438631,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    title: "Dune",
    video: false,
    vote_average: 7.9,
    popularity: 877.96,
    media_type: "movie",
  },
  {
    vote_average: 8.2,
    id: 71912,
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    backdrop_path: "/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    vote_count: 3184,
    original_name: "The Witcher",
    origin_country: ["US"],
    original_language: "en",
    first_air_date: "2019-12-20",
    poster_path: "/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    genre_ids: [10765, 18, 10759],
    name: "The Witcher",
    popularity: 1061.288,
    media_type: "tv",
  },
  {
    poster_path: "/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
    original_name: "La Casa de Papel",
    origin_country: ["ES"],
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
    vote_count: 15784,
    vote_average: 8.3,
    first_air_date: "2017-05-02",
    backdrop_path: "/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
    name: "Money Heist",
    genre_ids: [80, 18],
    id: 71446,
    original_language: "es",
    popularity: 690.139,
    media_type: "tv",
  },
  {
    overview:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    release_date: "2021-09-01",
    adult: false,
    backdrop_path: "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg",
    vote_count: 4895,
    genre_ids: [28, 12, 14],
    original_title: "Shang-Chi and the Legend of the Ten Rings",
    original_language: "en",
    id: 566525,
    poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    title: "Shang-Chi and the Legend of the Ten Rings",
    video: false,
    vote_average: 7.8,
    popularity: 2274.893,
    media_type: "movie",
  },
  {
    genre_ids: [18, 36],
    original_language: "en",
    original_title: "The Last Duel",
    poster_path: "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
    video: false,
    vote_average: 7.6,
    vote_count: 1288,
    overview:
      "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
    id: 617653,
    title: "The Last Duel",
    release_date: "2021-10-13",
    adult: false,
    backdrop_path: "/mFbS5TwN95BcSEfiztdchLgTQ0v.jpg",
    popularity: 1130.191,
    media_type: "movie",
  },
  {
    release_date: "2019-06-28",
    adult: false,
    backdrop_path: "/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg",
    genre_ids: [28, 12, 878],
    vote_average: 7.5,
    original_language: "en",
    id: 429617,
    poster_path: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    vote_count: 11641,
    video: false,
    title: "Spider-Man: Far From Home",
    original_title: "Spider-Man: Far From Home",
    overview:
      "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
    popularity: 1013.942,
    media_type: "movie",
  },
  {
    id: 71914,
    backdrop_path: "/1P3QtW1IkivqDrKbbwuR0zCYIf8.jpg",
    original_name: "The Wheel of Time",
    genre_ids: [10765, 18],
    original_language: "en",
    name: "The Wheel of Time",
    vote_count: 885,
    vote_average: 8.0,
    poster_path: "/mpgDeLhl8HbhI03XLB7iKO6M6JE.jpg",
    overview:
      "Follow Moiraine, a member of the shadowy and influential all-female organization called the “Aes Sedai” as she embarks on a dangerous, world-spanning journey with five young men and women. Moiraine believes one of them might be the reincarnation of an incredibly powerful individual, whom prophecies say will either save humanity or destroy it.",
    first_air_date: "2021-11-18",
    origin_country: ["US"],
    popularity: 1424.556,
    media_type: "tv",
  },
  {
    id: 96777,
    backdrop_path: "/9hNJ3fvIVd4WE3rU1Us2awoTpgM.jpg",
    genre_ids: [18, 10765],
    original_language: "ko",
    poster_path: "/fFT0IgqtCOks4munDTxQwkvNJkd.jpg",
    vote_count: 137,
    vote_average: 8.2,
    overview:
      "During a perilous 24-hour mission on the moon, space explorers try to retrieve samples from an abandoned research facility steeped in classified secrets.",
    first_air_date: "2021-12-24",
    name: "The Silent Sea",
    origin_country: ["KR"],
    original_name: "고요의 바다",
    popularity: 272.744,
    media_type: "tv",
  },
];

export { mockTrending };
